config/routes.rb
Rails.application.routes.draw do
  root 'staic_page#home'
  resources :posts do
    resources :comments
  end
  resources :posts do
    resources :likes
  end
  resources :relationships, only: [:create, :destroy]

  get '/singup', to:'users#new'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: 'sessions#destroy'

  resources :users do
    member do
    get :following, :followers
    end
    end
    mount Commontator::Engine => '/commontator'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_commontator
    has_many :following, through: :active_relationships, source: :followed
    has_many :followed_users, foreign_key: :follower_id, class_name: "Follow"
has_many :followees, through: :followed_users, source: :person_being_followed
has_many :following_users, foreign_key: :followee_id, class_name: "Follow"
has_many :followers, through: :following_users, source: :person_doing_the_following
    has_many :followed_users, foreign_key: :follower_id, class_name:    
    "Follow"
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name:    
    "Follow"
    has_many :followers, through: :following_users
    has_many :likes, dependent: :destroy
    has_many :posts, dependent: :destroy
    has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",
    dependent:
    :destroy
    has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id",
    dependent:
    :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
        end
        def feed
            Post.where("user_id IN (SELECT followed_id FROM relationships
                             WHERE  follower_id = :user_id)
                             OR user_id = :user_id", user_id: id)
          end
        
          def follow(other_user)
            following << (other_user)
          end
        
          # Unfollows a user.
          def unfollow(other_user)
            following.delete(other_user)
          end
        
          # Returns true if the current user is following the other user.
          def following?(other_user)
            following.include?(other_user)
          end
        
        end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show
  before_action :logged_in_user, only: [:show,:index, :edit, :update, :destroy,
    :following, :followers]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @posts=@user.posts.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
    log_in @user
    flash[:success] = "Welcome to the Sample App!"
    redirect_to @user
    else
    render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
    end
    def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
    end
  private
    # Use callbacks to share common setup or constraints between actions.
  
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email,:password,:password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
<div><%= hidden_field_tag :followed_id%></div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.name %>
  <div id="follow_form">
  <% if current_user.follow?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with(model: @user, local: true) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
<p>Have account? <%= link_to "log in", login_path %></p>
</div>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
html: { method: :delete }, local: true) do |f| %>
<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>

<%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
<% @users.each do |user| %>
<%= render user %>
<% end %>
</ul>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'users/follow' if logged_in? %>
 <section class="user_info">
        <%= render 'relationships/user_info' %>
      </section>
<%= render 'relationships/stats' %>
    <%= render 'follow_form' if logged_in? %>
    <% if @user.posts.any? %>
      <h3>posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @user.posts %>
        
      </ol>
     <section class="post_form">
        <%= render 'posts/form' %>
        
      </section>
    <% end %>
  </div>
</div>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.posts.any? %>
      <h3>posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
<%= link_to 'Back', users_path %>

app/views/users/show_follow.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>

<span><b>post:</b> <%= @user.posts.count %></span>
</section>
</div>

</section>
</aside>
<div class="col-md-8">
<h3><%= @title %></h3>
<% if @users.any? %>
<ul class="users follow">
<%= render @users %>
</ul>
<%= will_paginate %>
<% end %>
</div>